<?xml version="1.0"?>
<!DOCTYPE LIGO_LW [
<!ELEMENT LIGO_LW ((LIGO_LW|Comment|Param|Time|Table|Array|Stream)*)>
<!ATTLIST LIGO_LW Name CDATA #IMPLIED Type CDATA #IMPLIED>
<!ELEMENT Comment (#PCDATA)>
<!ELEMENT Param (#PCDATA)>
<!ATTLIST Param Name CDATA #IMPLIED Type CDATA #IMPLIED Dim CDATA #IMPLIED
                Unit CDATA #IMPLIED>
<!ELEMENT Table (Comment?,Column*,Stream?)>
<!ATTLIST Table Name CDATA #IMPLIED Type CDATA #IMPLIED>
<!ELEMENT Column EMPTY>
<!ATTLIST Column Name CDATA #IMPLIED Type CDATA #IMPLIED Unit CDATA #IMPLIED>
<!ELEMENT Array (Dim*,Stream?)>
<!ATTLIST Array Name CDATA #IMPLIED Type CDATA #IMPLIED>
<!ELEMENT Dim (#PCDATA)>
<!ATTLIST Dim Name CDATA #IMPLIED>
<!ELEMENT Stream (#PCDATA)>
<!ATTLIST Stream Name CDATA #IMPLIED Type (Remote|Local) "Local"
          Delimiter CDATA "," Encoding CDATA #IMPLIED Content CDATA #IMPLIED>
<!ELEMENT Time (#PCDATA)>
<!ATTLIST Time Name CDATA #IMPLIED Type (GPS|Unix|ISO-8601) "ISO-8601">
]>
<LIGO_LW Name="Diagnostics Test">
  <LIGO_LW Name="Header" Type="Global">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="Creator" Type="string">Diagnostics system</Param>
    <Param Name="TestType" Type="string">FFT</Param>
    <Param Name="TestName" Type="string">1998-2001, by Daniel Sigg</Param>
    <Param Name="Supervisory" Type="string">Standard</Param>
    <Param Name="TestIterator" Type="string">Repeat</Param>
    <Time Name="TestTime" Type="GPS">1297380087.0</Time>
    <Time Name="TestTimeUTC" Type="ISO-8601">2021-02-14 23:21:09</Time>
    <Param Name="InputSource" Type="string">online</Param>
    <Param Name="Comment" Type="string"></Param>
  </LIGO_LW>
  <LIGO_LW Name="Def" Type="Defaults">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="AllowCancel" Type="boolean">true</Param>
    <Param Name="NoStimulus" Type="boolean">false</Param>
    <Param Name="NoAnalysis" Type="boolean">false</Param>
    <Param Name="KeepTraces" Type="int">100</Param>
    <Param Name="SiteDefault" Type="byte">.</Param>
    <Param Name="SiteForce" Type="byte"> </Param>
    <Param Name="IfoDefault" Type="byte"> </Param>
    <Param Name="IfoForce" Type="byte"> </Param>
    <Param Name="Reconnect" Type="boolean">false</Param>
    <Param Name="PlotWindowLayout[1]" Type="int">102</Param>
    <Param Name="PlotWindows" Type="int">1</Param>
    <Param Name="CalibrationRecords" Type="int">0</Param>
  </LIGO_LW>
  <LIGO_LW Name="Find" Type="Optimization">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="Enable" Type="boolean">true</Param>
    <Param Name="Change" Type="boolean">true</Param>
    <Param Name="Type" Type="int">0</Param>
    <Param Name="Value" Type="double">0</Param>
    <Param Name="Function" Type="int">0</Param>
    <Param Name="Param" Type="double" Dim="2">0	100</Param>
    <Param Name="Method" Type="int">0</Param>
  </LIGO_LW>
  <LIGO_LW Name="Lidax" Type="Fantom">
    <Param Name="Flag" Type="string">TestParameters</Param>
  </LIGO_LW>
  <LIGO_LW Name="Sync" Type="Synchronization">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="Type" Type="int">0</Param>
    <Time Name="Start" Type="GPS">1291543031.0</Time>
    <Param Name="Wait" Type="double" Unit="s">-0</Param>
    <Param Name="Repeat" Type="int">1</Param>
    <Param Name="RepeatRate" Type="double" Unit="s">0</Param>
    <Param Name="SlowDown" Type="double" Unit="s">0</Param>
  </LIGO_LW>
  <LIGO_LW Name="Test" Type="TestParameter">
    <Param Name="Flag" Type="string">TestParameters</Param>
    <Param Name="Subtype" Type="string">FFT</Param>
    <Param Name="StartFrequency" Type="double" Unit="Hz">0</Param>
    <Param Name="StopFrequency" Type="double" Unit="Hz">20</Param>
    <Param Name="BW" Type="double" Unit="Hz">0.03</Param>
    <Param Name="Overlap" Type="double">0.5</Param>
    <Param Name="Window" Type="int">1</Param>
    <Param Name="RemoveDC" Type="boolean">true</Param>
    <Param Name="AChannels" Type="int">5</Param>
    <Param Name="AverageType" Type="int">0</Param>
    <Param Name="Averages" Type="int">10</Param>
    <Param Name="BurstNoiseQuietTime_s" Type="double">0</Param>
    <Param Name="SettlingTime" Type="double">0.1</Param>
    <Param Name="RampDown" Type="double">1</Param>
    <Param Name="RampUp" Type="double">0</Param>
    <Param Name="StimulusType[0]" Type="int">7</Param>
    <Param Name="StimulusType[1]" Type="int">0</Param>
    <Param Name="StimulusType[2]" Type="int">0</Param>
    <Param Name="StimulusType[3]" Type="int">0</Param>
    <Param Name="StimulusType[4]" Type="int">0</Param>
    <Param Name="StimulusFrequency[0]" Type="double" Unit="Hz">0</Param>
    <Param Name="StimulusFrequency[1]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusFrequency[2]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusFrequency[3]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusFrequency[4]" Type="double" Unit="Hz">100</Param>
    <Param Name="StimulusAmplitude[0]" Type="double">30000</Param>
    <Param Name="StimulusAmplitude[1]" Type="double">0</Param>
    <Param Name="StimulusAmplitude[2]" Type="double">0</Param>
    <Param Name="StimulusAmplitude[3]" Type="double">0</Param>
    <Param Name="StimulusAmplitude[4]" Type="double">0</Param>
    <Param Name="StimulusOffset[0]" Type="double">0</Param>
    <Param Name="StimulusOffset[1]" Type="double">0</Param>
    <Param Name="StimulusOffset[2]" Type="double">0</Param>
    <Param Name="StimulusOffset[3]" Type="double">0</Param>
    <Param Name="StimulusOffset[4]" Type="double">0</Param>
    <Param Name="StimulusPhase[0]" Type="double">0</Param>
    <Param Name="StimulusPhase[1]" Type="double">0</Param>
    <Param Name="StimulusPhase[2]" Type="double">0</Param>
    <Param Name="StimulusPhase[3]" Type="double">0</Param>
    <Param Name="StimulusPhase[4]" Type="double">0</Param>
    <Param Name="StimulusRatio[0]" Type="double">0.5</Param>
    <Param Name="StimulusRatio[1]" Type="double">0.5</Param>
    <Param Name="StimulusRatio[2]" Type="double">0.5</Param>
    <Param Name="StimulusRatio[3]" Type="double">0.5</Param>
    <Param Name="StimulusRatio[4]" Type="double">0.5</Param>
    <Param Name="StimulusFrequencyRange[0]" Type="double" Unit="Hz">10</Param>
    <Param Name="StimulusFrequencyRange[1]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusFrequencyRange[2]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusFrequencyRange[3]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusFrequencyRange[4]" Type="double" Unit="Hz">10000</Param>
    <Param Name="StimulusAmplitudeRange[0]" Type="double">0</Param>
    <Param Name="StimulusAmplitudeRange[1]" Type="double">0</Param>
    <Param Name="StimulusAmplitudeRange[2]" Type="double">0</Param>
    <Param Name="StimulusAmplitudeRange[3]" Type="double">0</Param>
    <Param Name="StimulusAmplitudeRange[4]" Type="double">0</Param>
    <Param Name="MeasurementChannelRate[0]" Type="int">2048</Param>
    <Param Name="MeasurementChannel[0]" Type="string" Unit="channel">K1:VIS-ETMY_F0_DAMP_GAS_IN1</Param>
    <Param Name="MeasurementActive[0]" Type="boolean">true</Param>
    <Param Name="MeasurementChannelRate[1]" Type="int">2048</Param>
    <Param Name="MeasurementChannel[1]" Type="string" Unit="channel">K1:VIS-ETMY_F1_DAMP_GAS_IN1</Param>
    <Param Name="MeasurementActive[1]" Type="boolean">true</Param>
    <Param Name="MeasurementChannelRate[2]" Type="int">2048</Param>
    <Param Name="MeasurementChannel[2]" Type="string" Unit="channel">K1:VIS-ETMY_F2_DAMP_GAS_IN1</Param>
    <Param Name="MeasurementActive[2]" Type="boolean">true</Param>
    <Param Name="StimulusChannel[0]" Type="string" Unit="channel">K1:VIS-SR2_F1_TEST_GAS_EXC</Param>
    <Param Name="StimulusActive[0]" Type="boolean">true</Param>
    <Param Name="StimulusReadback[0]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusFilter[0]" Type="string"></Param>
    <Param Name="MeasurementChannelRate[3]" Type="int">2048</Param>
    <Param Name="MeasurementChannel[3]" Type="string" Unit="channel">K1:VIS-ETMY_F3_DAMP_GAS_IN1</Param>
    <Param Name="MeasurementActive[3]" Type="boolean">true</Param>
    <Param Name="MeasurementChannelRate[4]" Type="int">2048</Param>
    <Param Name="MeasurementChannel[4]" Type="string" Unit="channel">K1:VIS-SR2_F1_DAMP_GAS_IN1</Param>
    <Param Name="MeasurementActive[4]" Type="boolean">true</Param>
    <Param Name="MeasurementChannelRate[5]" Type="int">0</Param>
    <Param Name="MeasurementChannel[5]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[5]" Type="boolean">false</Param>
    <Param Name="StimulusChannel[1]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusActive[1]" Type="boolean">false</Param>
    <Param Name="StimulusReadback[1]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusFilter[1]" Type="string"></Param>
    <Param Name="StimulusChannel[2]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusActive[2]" Type="boolean">false</Param>
    <Param Name="StimulusReadback[2]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusFilter[2]" Type="string"></Param>
    <Param Name="StimulusChannel[3]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusActive[3]" Type="boolean">false</Param>
    <Param Name="StimulusReadback[3]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusFilter[3]" Type="string"></Param>
    <Param Name="StimulusChannel[4]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusActive[4]" Type="boolean">false</Param>
    <Param Name="StimulusReadback[4]" Type="string" Unit="channel"></Param>
    <Param Name="StimulusFilter[4]" Type="string"></Param>
    <Param Name="MeasurementChannelRate[6]" Type="int">2048</Param>
    <Param Name="MeasurementChannel[6]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[6]" Type="boolean">false</Param>
    <Param Name="MeasurementChannelRate[7]" Type="int">2048</Param>
    <Param Name="MeasurementChannel[7]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[7]" Type="boolean">false</Param>
    <Param Name="MeasurementChannelRate[8]" Type="int">0</Param>
    <Param Name="MeasurementChannel[8]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[8]" Type="boolean">false</Param>
    <Param Name="MeasurementChannelRate[9]" Type="int">0</Param>
    <Param Name="MeasurementChannel[9]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[9]" Type="boolean">false</Param>
    <Param Name="MeasurementChannelRate[10]" Type="int">0</Param>
    <Param Name="MeasurementChannel[10]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[10]" Type="boolean">false</Param>
    <Param Name="MeasurementChannelRate[11]" Type="int">0</Param>
    <Param Name="MeasurementChannel[11]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[11]" Type="boolean">false</Param>
    <Param Name="MeasurementChannelRate[12]" Type="int">0</Param>
    <Param Name="MeasurementChannel[12]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[12]" Type="boolean">false</Param>
    <Param Name="MeasurementChannelRate[13]" Type="int">0</Param>
    <Param Name="MeasurementChannel[13]" Type="string" Unit="channel"></Param>
    <Param Name="MeasurementActive[13]" Type="boolean">false</Param>
  </LIGO_LW>
  <LIGO_LW Name="Plot[1][0]" Type="Plot">
    <Param Name="Flag" Type="string">Settings</Param>
    <Param Name="Name" Type="string">Default</Param>
    <Param Name="TracesGraphType" Type="string">Transfer function</Param>
    <Param Name="TracesActive[0]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[0]" Type="string" Unit="channel">K1:VIS-SR2_F1_TEST_GAS_EXC</Param>
    <Param Name="TracesBChannel[0]" Type="string" Unit="channel">K1:VIS-SR2_F1_DAMP_GAS_IN1</Param>
    <Param Name="TracesActive[1]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[1]" Type="string" Unit="channel">K1:VIS-SR2_F1_TEST_GAS_EXC</Param>
    <Param Name="TracesBChannel[1]" Type="string" Unit="channel">K1:VIS-ETMY_F2_DAMP_GAS_IN1</Param>
    <Param Name="TracesActive[2]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[2]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCY_IN1</Param>
    <Param Name="TracesBChannel[2]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[3]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[3]" Type="string" Unit="channel">K1:VIS-ETMY_IP_TEST_L_EXC</Param>
    <Param Name="TracesBChannel[3]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[4]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[4]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[4]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[5]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[5]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[5]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[6]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[6]" Type="string" Unit="channel"></Param>
    <Param Name="TracesBChannel[6]" Type="string" Unit="channel"></Param>
    <Param Name="TracesActive[7]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[7]" Type="string" Unit="channel">K1:VIS-ETMY_BF_TEST_L_EXC(REF0)</Param>
    <Param Name="TracesBChannel[7]" Type="string" Unit="channel">K1:VIS-SR2_F1_DAMP_L_IN1(REF0)</Param>
    <Param Name="TracesPlotStyle" Type="int" Dim="8">0	0	0	0	0	0	0	0</Param>
    <Param Name="TracesLineAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesLineAttrStyle" Type="int" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesLineAttrWidth" Type="double" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesMarkerAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesMarkerAttrStyle" Type="int" Dim="8">20	22	21	23	29	27	2	5</Param>
    <Param Name="TracesMarkerAttrSize" Type="double" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesBarAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesBarAttrStyle" Type="int" Dim="8">1001	1001	1001	1001	1001	1001	1001	1001</Param>
    <Param Name="TracesBarAttrWidth" Type="double" Dim="8">0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.1</Param>
    <Param Name="RangeAxisScale" Type="int" Dim="2">1	0</Param>
    <Param Name="RangeRange" Type="int" Dim="2">0	0</Param>
    <Param Name="RangeRangeFrom" Type="double" Dim="2">0.028125	-140.381</Param>
    <Param Name="RangeRangeTo" Type="double" Dim="2">21.9969	-26.8224</Param>
    <Param Name="RangeBin" Type="int">1</Param>
    <Param Name="RangeBinLogSpacing" Type="boolean">true</Param>
    <Param Name="UnitsXValues" Type="int">0</Param>
    <Param Name="UnitsYValues" Type="int">1</Param>
    <Param Name="UnitsXUnit" Type="string">default</Param>
    <Param Name="UnitsYUnit" Type="string">default</Param>
    <Param Name="UnitsXMag" Type="int">0</Param>
    <Param Name="UnitsYMag" Type="int">0</Param>
    <Param Name="UnitsXSlope" Type="double">1</Param>
    <Param Name="UnitsYSlope" Type="double">1</Param>
    <Param Name="UnitsXOffset" Type="double">0</Param>
    <Param Name="UnitsYOffset" Type="double">0</Param>
    <Param Name="CursorActive" Type="boolean" Dim="2">false	false</Param>
    <Param Name="CursorTrace" Type="int">0</Param>
    <Param Name="CursorStyle" Type="int">1</Param>
    <Param Name="CursorType" Type="int">0</Param>
    <Param Name="CursorX" Type="double" Dim="2">0.0625	20</Param>
    <Param Name="CursorH" Type="double" Dim="2">0	100</Param>
    <Param Name="CursorValid" Type="boolean" Dim="8">true	false	false	false	false	false	false	false</Param>
    <Param Name="CursorN" Type="double" Dim="8">640	0	0	0	0	0	0	0</Param>
    <Param Name="CursorXDiff" Type="double" Dim="8">19.9688	19.9688	900	900	0	0	0	99.9922</Param>
    <Param Name="CursorYDiff" Type="double" Dim="8">-29.2171	-47.7591	-1.28289	-48.9368	0	0	0	-64.6881</Param>
    <Param Name="CursorMean" Type="double" Dim="8">-65.7135	0	0	0	0	0	0	0</Param>
    <Param Name="CursorRMS" Type="double" Dim="8">66.6171	0	0	0	0	0	0	0</Param>
    <Param Name="CursorStdDev" Type="double" Dim="8">10.9434	0	0	0	0	0	0	0</Param>
    <Param Name="CursorSum" Type="double" Dim="8">-42056.6	0	0	0	0	0	0	0</Param>
    <Param Name="CursorSqrSum" Type="double" Dim="8">2.84021e+06	0	0	0	0	0	0	0</Param>
    <Param Name="CursorArea" Type="double" Dim="8">-1314.27	0	0	0	0	0	0	0</Param>
    <Param Name="CursorRMSArea" Type="double" Dim="8">297.921	0	0	0	0	0	0	0</Param>
    <Param Name="CursorPeakX" Type="double" Dim="8">0.6875	0	0	0	0	0	0	0</Param>
    <Param Name="CursorPeakY" Type="double" Dim="8">-18.9856	0	0	0	0	0	0	0</Param>
    <Param Name="ConfigAutoConfig" Type="boolean">true</Param>
    <Param Name="ConfigRespectUser" Type="boolean">true</Param>
    <Param Name="ConfigAutoAxes" Type="boolean">true</Param>
    <Param Name="ConfigAutoBin" Type="boolean">true</Param>
    <Param Name="ConfigAutoTimeAdjust" Type="boolean">true</Param>
    <Param Name="StyleTitle" Type="string">SR2_F1_GAS</Param>
    <Param Name="StyleTitleAlign" Type="int">13</Param>
    <Param Name="StyleTitleAngle" Type="double">0</Param>
    <Param Name="StyleTitleColor" Type="int">1</Param>
    <Param Name="StyleTitleFont" Type="int">62</Param>
    <Param Name="StyleTitleSize" Type="double">0.07</Param>
    <Param Name="StyleMargin" Type="double" Dim="4">0.1	0.05	0.1	0.18</Param>
    <Param Name="AxisXTitle" Type="string">Frequency</Param>
    <Param Name="AxisXAxisAttrAxisColor" Type="int">1</Param>
    <Param Name="AxisXAxisAttrLabelColor" Type="int">1</Param>
    <Param Name="AxisXAxisAttrLabelFont" Type="int">62</Param>
    <Param Name="AxisXAxisAttrLabelOffset" Type="double">0.005</Param>
    <Param Name="AxisXAxisAttrLabelSize" Type="double">0.04</Param>
    <Param Name="AxisXAxisAttrNdividions" Type="int">510</Param>
    <Param Name="AxisXAxisAttrTickLength" Type="double">0.03</Param>
    <Param Name="AxisXAxisAttrTitleOffset" Type="double">1.4</Param>
    <Param Name="AxisXAxisAttrTitleSize" Type="double">0.042</Param>
    <Param Name="AxisXAxisAttrTitleColor" Type="int">1</Param>
    <Param Name="AxisXGrid" Type="boolean">true</Param>
    <Param Name="AxisXBothSides" Type="boolean">true</Param>
    <Param Name="AxisXCenterTitle" Type="boolean">true</Param>
    <Param Name="AxisYTitle" Type="string">Mag. [um/cnt or urad/cnt]</Param>
    <Param Name="AxisYAxisAttrAxisColor" Type="int">1</Param>
    <Param Name="AxisYAxisAttrLabelColor" Type="int">1</Param>
    <Param Name="AxisYAxisAttrLabelFont" Type="int">62</Param>
    <Param Name="AxisYAxisAttrLabelOffset" Type="double">0.005</Param>
    <Param Name="AxisYAxisAttrLabelSize" Type="double">0.04</Param>
    <Param Name="AxisYAxisAttrNdividions" Type="int">510</Param>
    <Param Name="AxisYAxisAttrTickLength" Type="double">0.03</Param>
    <Param Name="AxisYAxisAttrTitleOffset" Type="double">0.7</Param>
    <Param Name="AxisYAxisAttrTitleSize" Type="double">0.05</Param>
    <Param Name="AxisYAxisAttrTitleColor" Type="int">1</Param>
    <Param Name="AxisYGrid" Type="boolean">true</Param>
    <Param Name="AxisYBothSides" Type="boolean">true</Param>
    <Param Name="AxisYCenterTitle" Type="boolean">true</Param>
    <Param Name="LegendShow" Type="boolean">true</Param>
    <Param Name="LegendPlacement" Type="int">2</Param>
    <Param Name="LegendXAdjust" Type="double">0</Param>
    <Param Name="LegendYAdjust" Type="double">0</Param>
    <Param Name="LegendSymbolStyle" Type="int">0</Param>
    <Param Name="LegendTextStyle" Type="int">0</Param>
    <Param Name="LegendSize" Type="double">1.4</Param>
    <Param Name="LegendText[0]" Type="string"></Param>
    <Param Name="LegendText[1]" Type="string"></Param>
    <Param Name="LegendText[2]" Type="string"></Param>
    <Param Name="LegendText[3]" Type="string"></Param>
    <Param Name="LegendText[4]" Type="string"></Param>
    <Param Name="LegendText[5]" Type="string"></Param>
    <Param Name="LegendText[6]" Type="string"></Param>
    <Param Name="LegendText[7]" Type="string"></Param>
    <Param Name="ParamShow" Type="boolean">true</Param>
    <Param Name="ParamT0" Type="boolean">true</Param>
    <Param Name="ParamAvg" Type="boolean">true</Param>
    <Param Name="ParamSpecial" Type="boolean">true</Param>
    <Param Name="ParamTimeFormatUTC" Type="boolean">true</Param>
    <Param Name="ParamTextSize" Type="double">0.04</Param>
  </LIGO_LW>
  <LIGO_LW Name="Plot[1][1]" Type="Plot">
    <Param Name="Flag" Type="string">Settings</Param>
    <Param Name="Name" Type="string">Default</Param>
    <Param Name="TracesGraphType" Type="string">Transfer function</Param>
    <Param Name="TracesActive[0]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[0]" Type="string" Unit="channel">K1:VIS-SR2_F1_DAMP_GAS_IN1</Param>
    <Param Name="TracesBChannel[0]" Type="string" Unit="channel">K1:VIS-SR2_F1_TEST_GAS_EXC</Param>
    <Param Name="TracesActive[1]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[1]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCL_IN1</Param>
    <Param Name="TracesBChannel[1]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCY_IN1</Param>
    <Param Name="TracesActive[2]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[2]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCL_IN1</Param>
    <Param Name="TracesBChannel[2]" Type="string" Unit="channel">K1:VIS-ETMY_IP_TEST_L_EXC</Param>
    <Param Name="TracesActive[3]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[3]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCT_IN1</Param>
    <Param Name="TracesBChannel[3]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCL_IN1</Param>
    <Param Name="TracesActive[4]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[4]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCT_IN1</Param>
    <Param Name="TracesBChannel[4]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCY_IN1</Param>
    <Param Name="TracesActive[5]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[5]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCT_IN1</Param>
    <Param Name="TracesBChannel[5]" Type="string" Unit="channel">K1:VIS-ETMY_IP_TEST_L_EXC</Param>
    <Param Name="TracesActive[6]" Type="boolean">false</Param>
    <Param Name="TracesAChannel[6]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCY_IN1</Param>
    <Param Name="TracesBChannel[6]" Type="string" Unit="channel">K1:VIS-ETMY_IP_BLEND_ACCL_IN1</Param>
    <Param Name="TracesActive[7]" Type="boolean">true</Param>
    <Param Name="TracesAChannel[7]" Type="string" Unit="channel">K1:VIS-ETMY_BF_TEST_L_EXC(REF0)</Param>
    <Param Name="TracesBChannel[7]" Type="string" Unit="channel">K1:VIS-SR2_F1_DAMP_L_IN1(REF0)</Param>
    <Param Name="TracesPlotStyle" Type="int" Dim="8">1	0	0	0	0	0	0	1</Param>
    <Param Name="TracesLineAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesLineAttrStyle" Type="int" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesLineAttrWidth" Type="double" Dim="8">1	1	1	1	1	1	1	1</Param>
    <Param Name="TracesMarkerAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesMarkerAttrStyle" Type="int" Dim="8">24	22	21	23	29	27	2	24</Param>
    <Param Name="TracesMarkerAttrSize" Type="double" Dim="8">0.6	1	1	1	1	1	1	0.6</Param>
    <Param Name="TracesBarAttrColor" Type="int" Dim="8">2	4	3	28	6	7	5	1</Param>
    <Param Name="TracesBarAttrStyle" Type="int" Dim="8">1001	1001	1001	1001	1001	1001	1001	1001</Param>
    <Param Name="TracesBarAttrWidth" Type="double" Dim="8">0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.1</Param>
    <Param Name="RangeAxisScale" Type="int" Dim="2">1	0</Param>
    <Param Name="RangeRange" Type="int" Dim="2">0	0</Param>
    <Param Name="RangeRangeFrom" Type="double" Dim="2">0.028125	-215.976</Param>
    <Param Name="RangeRangeTo" Type="double" Dim="2">21.9969	215.943</Param>
    <Param Name="RangeBin" Type="int">1</Param>
    <Param Name="RangeBinLogSpacing" Type="boolean">true</Param>
    <Param Name="UnitsXValues" Type="int">0</Param>
    <Param Name="UnitsYValues" Type="int">5</Param>
    <Param Name="UnitsXUnit" Type="string">default</Param>
    <Param Name="UnitsYUnit" Type="string">default</Param>
    <Param Name="UnitsXMag" Type="int">0</Param>
    <Param Name="UnitsYMag" Type="int">0</Param>
    <Param Name="UnitsXSlope" Type="double">1</Param>
    <Param Name="UnitsYSlope" Type="double">1</Param>
    <Param Name="UnitsXOffset" Type="double">0</Param>
    <Param Name="UnitsYOffset" Type="double">0</Param>
    <Param Name="CursorActive" Type="boolean" Dim="2">true	false</Param>
    <Param Name="CursorTrace" Type="int">0</Param>
    <Param Name="CursorStyle" Type="int">1</Param>
    <Param Name="CursorType" Type="int">0</Param>
    <Param Name="CursorX" Type="double" Dim="2">1	20</Param>
    <Param Name="CursorH" Type="double" Dim="2">0	100</Param>
    <Param Name="CursorValid" Type="boolean" Dim="8">true	false	false	false	false	false	false	false</Param>
    <Param Name="CursorN" Type="double" Dim="8">609	0	0	0	0	0	0	0</Param>
    <Param Name="CursorXDiff" Type="double" Dim="8">19	900	900	899.938	899.938	899.938	899.938	99</Param>
    <Param Name="CursorYDiff" Type="double" Dim="8">12.5416	-0.357962	-0.329361	5.31104	-81.4666	105.097	-4.11241	50.2148</Param>
    <Param Name="CursorMean" Type="double" Dim="8">-84.3383	0	0	0	0	0	0	0</Param>
    <Param Name="CursorRMS" Type="double" Dim="8">100.038	0	0	0	0	0	0	0</Param>
    <Param Name="CursorStdDev" Type="double" Dim="8">53.8458	0	0	0	0	0	0	0</Param>
    <Param Name="CursorSum" Type="double" Dim="8">-51362	0	0	0	0	0	0	0</Param>
    <Param Name="CursorSqrSum" Type="double" Dim="8">6.0946e+06	0	0	0	0	0	0	0</Param>
    <Param Name="CursorArea" Type="double" Dim="8">-1605.06	0	0	0	0	0	0	0</Param>
    <Param Name="CursorRMSArea" Type="double" Dim="8">436.413	0	0	0	0	0	0	0</Param>
    <Param Name="CursorPeakX" Type="double" Dim="8">4.875	0	0	0	0	0	0	0</Param>
    <Param Name="CursorPeakY" Type="double" Dim="8">13.7732	0	0	0	0	0	0	0</Param>
    <Param Name="ConfigAutoConfig" Type="boolean">true</Param>
    <Param Name="ConfigRespectUser" Type="boolean">true</Param>
    <Param Name="ConfigAutoAxes" Type="boolean">true</Param>
    <Param Name="ConfigAutoBin" Type="boolean">true</Param>
    <Param Name="ConfigAutoTimeAdjust" Type="boolean">true</Param>
    <Param Name="StyleTitle" Type="string">SR2_F1_GAS</Param>
    <Param Name="StyleTitleAlign" Type="int">13</Param>
    <Param Name="StyleTitleAngle" Type="double">0</Param>
    <Param Name="StyleTitleColor" Type="int">1</Param>
    <Param Name="StyleTitleFont" Type="int">62</Param>
    <Param Name="StyleTitleSize" Type="double">0.07</Param>
    <Param Name="StyleMargin" Type="double" Dim="4">0.1	0.05	0.1	0.18</Param>
    <Param Name="AxisXTitle" Type="string">Frequency</Param>
    <Param Name="AxisXAxisAttrAxisColor" Type="int">1</Param>
    <Param Name="AxisXAxisAttrLabelColor" Type="int">1</Param>
    <Param Name="AxisXAxisAttrLabelFont" Type="int">62</Param>
    <Param Name="AxisXAxisAttrLabelOffset" Type="double">0.005</Param>
    <Param Name="AxisXAxisAttrLabelSize" Type="double">0.04</Param>
    <Param Name="AxisXAxisAttrNdividions" Type="int">510</Param>
    <Param Name="AxisXAxisAttrTickLength" Type="double">0.03</Param>
    <Param Name="AxisXAxisAttrTitleOffset" Type="double">1.4</Param>
    <Param Name="AxisXAxisAttrTitleSize" Type="double">0.042</Param>
    <Param Name="AxisXAxisAttrTitleColor" Type="int">1</Param>
    <Param Name="AxisXGrid" Type="boolean">true</Param>
    <Param Name="AxisXBothSides" Type="boolean">true</Param>
    <Param Name="AxisXCenterTitle" Type="boolean">true</Param>
    <Param Name="AxisYTitle" Type="string">Phase</Param>
    <Param Name="AxisYAxisAttrAxisColor" Type="int">1</Param>
    <Param Name="AxisYAxisAttrLabelColor" Type="int">1</Param>
    <Param Name="AxisYAxisAttrLabelFont" Type="int">62</Param>
    <Param Name="AxisYAxisAttrLabelOffset" Type="double">0.005</Param>
    <Param Name="AxisYAxisAttrLabelSize" Type="double">0.04</Param>
    <Param Name="AxisYAxisAttrNdividions" Type="int">510</Param>
    <Param Name="AxisYAxisAttrTickLength" Type="double">0.03</Param>
    <Param Name="AxisYAxisAttrTitleOffset" Type="double">0.7</Param>
    <Param Name="AxisYAxisAttrTitleSize" Type="double">0.05</Param>
    <Param Name="AxisYAxisAttrTitleColor" Type="int">1</Param>
    <Param Name="AxisYGrid" Type="boolean">true</Param>
    <Param Name="AxisYBothSides" Type="boolean">true</Param>
    <Param Name="AxisYCenterTitle" Type="boolean">true</Param>
    <Param Name="LegendShow" Type="boolean">true</Param>
    <Param Name="LegendPlacement" Type="int">2</Param>
    <Param Name="LegendXAdjust" Type="double">0</Param>
    <Param Name="LegendYAdjust" Type="double">0</Param>
    <Param Name="LegendSymbolStyle" Type="int">0</Param>
    <Param Name="LegendTextStyle" Type="int">0</Param>
    <Param Name="LegendSize" Type="double">1.4</Param>
    <Param Name="LegendText[0]" Type="string"></Param>
    <Param Name="LegendText[1]" Type="string"></Param>
    <Param Name="LegendText[2]" Type="string"></Param>
    <Param Name="LegendText[3]" Type="string"></Param>
    <Param Name="LegendText[4]" Type="string"></Param>
    <Param Name="LegendText[5]" Type="string"></Param>
    <Param Name="LegendText[6]" Type="string"></Param>
    <Param Name="LegendText[7]" Type="string"></Param>
    <Param Name="ParamShow" Type="boolean">true</Param>
    <Param Name="ParamT0" Type="boolean">true</Param>
    <Param Name="ParamAvg" Type="boolean">true</Param>
    <Param Name="ParamSpecial" Type="boolean">true</Param>
    <Param Name="ParamTimeFormatUTC" Type="boolean">true</Param>